#!/usr/bin/env python

from mpi.compiler import run_compiler

import argparse
import logging

def parse_args():
    parser = argparse.ArgumentParser(
        prog='mpi',
        description='MariusGNN MPI compiler')
    parser.add_argument('pyfiles', nargs='+')
    parser.add_argument('-l', '--log', default='WARNING')
    return parser.parse_args()

def main():
    args = parse_args()

    # Setup logging
    log_level = getattr(logging, args.log.upper(), None)
    if not isinstance(log_level, int):
        raise ValueError(f'Invalid log level: {args.log}')

    logging.basicConfig(level=log_level, format='[%(levelname)s]\t%(message)s')

    # Compile each file
    for filename in args.pyfiles:
        run_compiler(filename)

if __name__ == '__main__':
    main()
